name: Backend workflow

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
